grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2

model_selection:
  module_0:
    class: RandomForestClassifier
    class_weight: {0:0.15,1:0.85}
    random_state: 1
    module: sklearn.linear_model
    params:
      n_estimators: np.arange(251,501)
      min_samples_leaf": np.arange(1,6,1)
      max_features : ["log2",0.7,0.9,"auto"]
      max_samples: np.arange(0.3, 0.7, None)
    search_param_grid:  
      n_estimators:
      - 110      
      min_samples_leaf:
      -4
      
  module_1:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      learning_rate: 0.75
      random_state: 1
     search_param_grid:
       learning_rate: 
       - 1
    